server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  add_header Referrer-Policy "no-referrer" always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header X-Frame-Options "DENY" always;
  add_header Content-Security-Policy "default-src 'self'; connect-src 'self' https://www.google.com https://www.gstatic.com https://www.googletagmanager.com https://www.google-analytics.com https://region1.google-analytics.com https://analytics.google.com https://stats.g.doubleclick.net; style-src 'self' 'unsafe-inline'; script-src 'self' https://www.google.com https://www.gstatic.com https://www.googletagmanager.com; frame-src https://www.google.com; img-src 'self' data: https://www.google-analytics.com https://stats.g.doubleclick.net; frame-ancestors 'none'; base-uri 'none'; form-action 'self'" always;

  location /api/ {
    proxy_pass http://api:8081/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /health {
    proxy_pass http://api:8081/health;
  }

  location / {
    try_files $uri /index.html;
  }
}
